### ISSUE TITLE
Problem with CC/BCC

### ISSUE THREAD

**Issue by ubay25** [stackkit/laravel-database-emails#42] opened 2022-09-11 19:18 UTC
The package works fine but if you add cc the email is not being sent to the email address on the cc. So the below code will be sent to john@doe.com but not for jane@doe.com.

Email::compose()
    ->label('welcome')
    ->recipient('john@doe.com')
    ->cc('jane@doe.com')
    ->subject('This is a test')
    ->view('emails.welcome')
    ->variables([ 'name' => 'John Doe' ])
    ->send();

**Comment by marickvantuil** [comment] 2022-09-16 14:13
What are your PHP, Laravel and package version? I am unable to reproduce this issue.

<img width="472" alt="Screenshot 2022-09-16 at 16 10 58" src="https://user-images.githubusercontent.com/647007/190659305-a6617f79-1d82-4bb6-b3ff-eb6885736180.png">

**Comment by ubay25** [comment] 2022-09-16 14:25
Thanks for your reply!

PHP 7.3.11
Laravel 8
stackkit/laravel-database-emails 6.0.0

I know from your screenshot it's showing Cc: so does in mine. But the actual recipient on the Cc does not get a coy of the email.
Hope this helps, thanks!

**Comment by marickvantuil** [comment] 2022-10-15 15:40
Apologies for getting back so late!

If the e-mail client also shows the Cc, then we know for sure the recipient was added successfully. Whether the e-mail was actually *delivered*, is another story (and out of the scope of this package). Something might be up there. E-mail senders like Mailgun have detailed information whether a message was delivered or not, with specification as to why it might not work. Could you please check that?

I'll close this now because I cannot fix this afaik!

**Closed by marickvantuil** 2022-10-15 15:40 UTC
